In [1]:
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()
iris

In [6]:
import pandas as pd
df_iris = pd.DataFrame(iris.data)
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [7]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')
df_iris.to_sql('iris_resource', connect, if_exists='append', index=False)

In [8]:
df_load = pd.read_sql_query('select * from iris_resource', connect)
df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [9]:
x_data = df_load.to_numpy()
x_data.shape

(150, 4)

In [12]:
import numpy as np

In [13]:
y_data = iris.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

In [21]:
import tensorflow as tf

In [22]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(4,))) # input

model.add(tf.keras.layers.Dense(64, activation='relu')) # hidden
model.add(tf.keras.layers.Dense(64, activation='relu')) # hidden

model.add(tf.keras.layers.Dense(3, activation='softmax')) # output

model.compile(optimizer='adam', loss='mse', metrics=['acc']) # gadget

In [ ]:
model.summary()

In [23]:
model.fit(x_data, y_data, epochs=50, validation_split=0.3) # education

Epoch 1/50
4/4 [==============================] - 1s 61ms/step - loss: 0.4081 - acc: 0.6286 - val_loss: 2.7865 - val_acc: 0.0000e+00
Epoch 2/50
4/4 [==============================] - 0s 10ms/step - loss: 0.4003 - acc: 0.3619 - val_loss: 2.7784 - val_acc: 0.0444
Epoch 3/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3996 - acc: 0.0762 - val_loss: 2.7800 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3977 - acc: 0.2571 - val_loss: 2.7820 - val_acc: 0.0000e+00
Epoch 5/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3977 - acc: 0.0095 - val_loss: 2.7792 - val_acc: 0.0000e+00
Epoch 6/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3970 - acc: 0.0095 - val_loss: 2.7780 - val_acc: 0.9333
Epoch 7/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3971 - acc: 0.0381 - val_loss: 2.7781 - val_acc: 0.9556
Epoch 8/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3970 - acc: 0.

# Evaluation

In [24]:
model.evaluate(x_data, y_data) # 정확도 0.35 (35%)

5/5 [==============================] - 0s 2ms/step - loss: 1.1111 - acc: 0.3533


[1.1111177206039429, 0.35333332419395447]

# Service

In [26]:
x_data[25], y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [28]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.33084202, 0.33650512, 0.33265296]], dtype=float32)

In [29]:
np.argmax(pred)

1