In [1]:
import tensorflow as tf

In [2]:
loaded_model = tf.keras.models.load_model('./NaverSentimentAnalysis_LSTM.h5')
loaded_model

In [ ]:
!python -m pip install konlpy

In [4]:
import konlpy

In [5]:
words = list()
for tok in temp_x:
  if tok no in stopwords:
    words.append(tok)

In [6]:
import pickle

In [8]:
stopwords = pickle.load(open('./stopwords.pkl', 'rb'))
print(stopwords)

['의', '가', '이', '은', '들', '는', '좀', '잘', '걍', '과', '도', '를', '으로', '자', '에', '와', '한', '하다']


In [9]:
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('감독이 예술이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
new_sentence

['감독', '예술', '이네', '.']

In [10]:
tokenizer = pickle.load(open('./tokenizer.pkl', 'rb'))
tokenizer

In [12]:
vob_size = len(tokenizer.word_index)
vob_size

1572

In [15]:
# encoded = tokenizer.texts_to_sequences([new_sentence])
# encoded
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  92, 128,   1]],
      dtype=int32)

In [17]:
score = loaded_model.predict(pad_new)
score

array([[0.5053071]], dtype=float32)

In [18]:
if (score > 0.5):
  print('긍정', score*100)
else:
  print('부정', score*100)

긍정 [[50.53071]]


In [ ]:
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('감독이 예술이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
encoded = tokenizer.texts_to_sequences([new_sentence])
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
score = loaded_model.predict(pad_new)

In [20]:
def sentiment_predict(sentence):
  okt = konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence, stem=True)
  new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
  score = loaded_model.predict(pad_new)
  return score

In [25]:
words = '이 영화 꽝이네'
sentiment_predict(words)

array([[0.5111038]], dtype=float32)

In [27]:
words = '영화를 보니 속이 편해졌습니다'
sentiment_predict(words)

array([[0.5100444]], dtype=float32)