In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [3]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [4]:
range(len(note_seq)-4)

range(0, 50)

In [5]:
dataset = list()
for i in range(len(note_seq)-3):
  subset = note_seq[i:i+4]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item])
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2]]


In [6]:
import numpy as np

In [7]:
datasets = np.array(dataset)

In [8]:
x_train = datasets[:,0:3]
x_train.shape, #x_train

((51, 3),)

In [9]:
y_train = datasets[:,3]
y_train.shape, #y_train

((51,),)

In [10]:
len(code2idx)

14

In [11]:
x_train = x_train / 13 # len(code2idx)
x_train[3]

array([0.76923077, 0.61538462, 0.07692308])

# make model

In [12]:
import tensorflow as tf

In [13]:
x_train.shape, x_train[2]

((51, 3), array([0.15384615, 0.76923077, 0.61538462]))

In [14]:
X_train = np.reshape(x_train, (-1, 3, 1))
X_train.shape, X_train[2]

((51, 3, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462]]))

In [15]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [16]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(3, 1)))
model.add(tf.keras.layers.LSTM(128)) # (batch_size, timesteps, input_dim)
model.add(tf.keras.layers.Dense(14, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [26]:
hist = model.fit(X_train, y_train, epochs=500, batch_size=10)

Epoch 1/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0652 - accuracy: 0.5686
Epoch 2/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0919 - accuracy: 0.5490
Epoch 3/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0473 - accuracy: 0.5490
Epoch 4/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0581 - accuracy: 0.5490
Epoch 5/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0416 - accuracy: 0.6078
Epoch 6/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0366 - accuracy: 0.6275
Epoch 7/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0542 - accuracy: 0.6078
Epoch 8/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0493 - accuracy: 0.5882
Epoch 9/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0517 - accuracy: 0.6078
Epoch 10/500
6/6 [==============================] - 0s 5ms/step - loss: 1.0586 - accuracy: 0.6078
Epoch 11/500
6/6 [===========

In [18]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 8ms/step - loss: 2.4623 - accuracy: 0.3333


[2.462268829345703, 0.3333333432674408]

In [25]:
X_train[0:1]

array([[[0.84615385],
        [0.69230769],
        [0.15384615]]])

In [27]:
model.predict(X_train[0:1])

array([[6.3580319e-07, 4.4194752e-04, 1.5752498e-02, 9.8802397e-05,
        9.1378985e-04, 7.0886978e-07, 5.8013171e-07, 1.7947455e-01,
        7.1770307e-03, 2.0259745e-02, 7.6679939e-01, 9.0789907e-03,
        8.0252499e-07, 5.5807328e-07]], dtype=float32)

In [21]:
first = 0.61538462
second = 0.07692308
third = 0.53846154

In [31]:
pred = model.predict(X_train[0:1])

In [33]:
np.argmax(pred)

10